import { expect, test } from '@playwright/test'

test('renders the visual Suno workflow shell', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Visual music generation operating app' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Perfect lipsync gate' })).toBeHidden()
  await expect(page.getByRole('button', { name: /Open music video lane/i })).toBeDisabled()
  await page.getByRole('textbox', { name: 'Brief' }).fill('Neon khaliji club hook')
  await page.getByRole('textbox', { name: 'Lyrics' }).fill('Verse pre chorus')
  await page.getByRole('textbox', { name: 'Style' }).fill('Gulf percussion and electro-pop')
  await page.getByRole('textbox', { name: 'Voice' }).fill('Consented bright tenor persona')
  await page.getByRole('button', { name: /Generate mock Suno batch/i }).click()
  await page.getByRole('button', { name: /Neon khaliji club hook v2/i }).click()
  await expect(page.getByRole('button', { name: /Open music video lane/i })).toBeEnabled()
  await page.getByRole('button', { name: /Open music video lane/i }).click()
  await expect(page.getByRole('heading', { name: 'Perfect lipsync gate' })).toBeVisible()
  await expect(page.getByText(/segment drift/)).toBeVisible()
  await expect(page.getByText(/post-stitch/)).toBeVisible()
  await expect(page.getByText(/Music video source: mock-track-2/)).toBeVisible()
})
