import { expect, test } from '@playwright/test'
import type { TestInfo } from '@playwright/test'

function projectIdFor(testInfo: TestInfo): string {
  return `e2e-${testInfo.title.replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '').toLowerCase()}`
}

function projectUrl(testInfo: TestInfo): string {
  return `/?projectId=${encodeURIComponent(projectIdFor(testInfo))}`
}

test.beforeEach(async ({ page }, testInfo) => {
  await page.goto(projectUrl(testInfo))
  await page.evaluate(() => localStorage.clear())
})

test.setTimeout(120_000)

test('renders the visual Suno workflow shell', async ({ page }, testInfo) => {
  await page.goto(projectUrl(testInfo))
  await expect(page.getByRole('heading', { name: 'The Kantikal' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Lyric command room' })).toBeVisible()
  await expect(page.getByRole('article', { name: 'Lyric document' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'No selected source track' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Generate Suno batch' })).toBeVisible()
  await expect(page.getByLabel('Runtime status')).toContainText(/Suno web \/ Printing Press/)
  await expect(page.getByLabel('Runtime status')).toContainText(/optional adapter/)
  await expect(page.getByLabel('Runtime status')).toContainText(/ComfyUI/)
  await expect(page.getByRole('heading', { name: 'Perfect lipsync gate' })).toBeHidden()
  await expect(page.getByRole('button', { name: /Open music video lane/i })).toBeDisabled()
  await page.getByRole('textbox', { name: 'Brief' }).fill('Neon khaliji club hook')
  await page.getByRole('textbox', { name: 'Lyrics' }).fill('Verse pre chorus')
  await page.getByRole('textbox', { name: 'Style' }).fill('Gulf percussion and electro-pop')
  await page.getByRole('textbox', { name: 'Voice' }).fill('Consented bright tenor persona')
  await page.getByRole('button', { name: /Source assets: 2 assets/i }).click()
  await expect(page.getByRole('heading', { name: 'Project asset library' })).toBeVisible()
  await expect(page.getByText(/asset-lyrics-draft available/i)).toBeVisible()
  await page.getByRole('button', { name: /Import reference audio/i }).click()
  await expect(page.getByText(/asset-reference-audio-3 blocked/i)).toBeVisible()
  await expect(page.getByText(/uploadReferenceAudio blocked/i)).toBeVisible()
  await page.getByRole('button', { name: /Generate cover art asset/i }).click()
  await expect(page.getByText(/asset-cover-art-4 blocked/i)).toBeVisible()
  await expect(page.getByText(/generateCoverArt blocked/i)).toBeVisible()
  await page.getByRole('button', { name: /Plan video reference/i }).click()
  await expect(page.getByText(/asset-video-reference-5 blocked/i)).toBeVisible()
  await expect(page.getByText(/renderMusicVideo blocked/i)).toBeVisible()
  await page.getByRole('button', { name: /Voice \/ persona/i }).click()
  await expect(page.getByRole('heading', { name: 'Persona workbench' })).toBeVisible()
  await page.getByRole('button', { name: /Create persona reference/i }).click()
  await expect(page.getByText(/Consented bright tenor persona blocked/i)).toBeVisible()
  await page.getByRole('button', { name: /Generate Suno batch/i }).click()
  await expect(page.getByRole('button', { name: /Generation batch: 2 Suno variants from task_generate/i })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Choose source track' })).toBeVisible()
  await page.getByRole('button', { name: /Neon khaliji club hook provider take 2/i }).click()
  await expect(page.getByRole('heading', { name: /Neon khaliji club hook provider take 2/i })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Analyze waveform' })).toBeVisible()
  await expect(page.getByLabel('Waveform detection envelope')).toContainText(/No waveform analysis/)
  await page.getByRole('button', { name: 'Analyze waveform' }).first().click()
  await expect(page.getByRole('heading', { name: 'Audio Intelligence' }).last()).toBeVisible()
  await expect(page.getByLabel('Audio Intelligence waveform metrics')).toContainText(/transients/i)
  await expect(page.getByLabel('Audio Intelligence section energy')).toContainText(/hook/i)
  await expect(page.getByRole('heading', { name: 'Open Song Lab' })).toBeVisible()
  await page.getByRole('button', { name: /Downloads \/ exports/i }).click()
  await expect(page.getByRole('heading', { name: 'Provider export manager' })).toBeVisible()
  await page.getByRole('button', { name: /Poll selected generation job/i }).click()
  await expect(page.getByText(/Get music generation details ready/i)).toBeVisible()
  await expect(page.getByText(/HTTP provider export route produced fixture downloadable outputs/i).first()).toBeVisible()
  await expect(page.getByText(/audio ready/i)).toBeVisible()
  await expect(page.getByText(/cover-art ready/i)).toBeVisible()
  await expect(page.getByText(/stem ready/i)).toBeVisible()
  await page.getByRole('button', { name: /Source assets:/i }).click()
  await expect(page.getByText(/asset-generated-audio-/i)).toBeVisible()
  await page.getByRole('button', { name: /Version comparison/i }).click()
  await page.getByRole('button', { name: /Rate task_generate-track-2 as taste match/i }).click()
  await page.getByRole('button', { name: /Compare task_generate-track-1 vs task_generate-track-2/i }).click()
  await expect(page.getByText(/Taste score: 5/i)).toBeVisible()
  await expect(page.getByText(/winner task_generate-track-2/i)).toBeVisible()
  await page.getByRole('button', { name: /Song Lab/i }).click()
  await page.locator('button').filter({ hasText: 'Open Song Lab' }).click()
  await expect(page.getByRole('heading', { name: 'Song Lab' })).toBeVisible()
  await expect(page.getByText(/Source track: task_generate-track-2/i)).toBeVisible()
  await expect(page.getByText(/Source assets: asset-lyrics-draft/i)).toContainText(/asset-cover-art-4/i)
  await expect(page.getByText(/Source assets: asset-lyrics-draft/i)).toContainText(/asset-video-reference-5/i)
  await page.getByRole('button', { name: /Lock hook region/i }).click()
  await page.getByRole('button', { name: /Queue replace section/i }).click()
  await expect(page.getByText(/Hook locked/i)).toBeVisible()
  await expect(page.getByText(/songlab-edit-1 queued/i)).toBeVisible()
  await page.getByRole('button', { name: /Save selected to local library/i }).click()
  await expect(page.getByRole('heading', { name: 'Local library' })).toBeVisible()
  await expect(page.getByText(/Provider library API unsupported/i).last()).toBeVisible()
  await expect(page.getByText(/task_generate-track-2 saved locally/i)).toBeVisible()
  await page.getByRole('button', { name: /Run API action Create song/i }).click()
  await expect(page.getByRole('status')).toContainText(/Create song/i)
  await expect(page.getByRole('status')).toContainText(/server provider adapter/i)
  await page.getByRole('button', { name: /Run API action Library list\/search/i }).click()
  await expect(page.getByRole('status')).toContainText(/Library list\/search/i)
  await page.getByRole('button', { name: /Job queue/i }).click()
  await expect(page.getByRole('heading', { name: 'Job queue' })).toBeVisible()
  await expect(page.getByText(/Create song completed/i).last()).toBeVisible()
  await expect(page.getByText(/Library list\/search unsupported/i).last()).toBeVisible()
  await expect(page.getByRole('button', { name: /Open music video lane/i })).toBeEnabled()
  await page.getByRole('button', { name: /Open music video lane/i }).click()
  await expect(page.getByRole('heading', { name: 'Perfect lipsync gate' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Scene cards' })).toBeVisible()
  await expect(page.getByText(/Hook scene/i)).toBeVisible()
  await expect(page.getByText(/65s-108s/i)).toBeVisible()
  await expect(page.getByText(/ComfyUI render worker planned/i)).toBeVisible()
  await page.getByRole('button', { name: /Plan ComfyUI render graph/i }).click()
  await expect(page.getByText(/wan-video-lipsync/i).first()).toBeVisible()
  await expect(page.getByText(/Reference assets/i)).toContainText(/asset-cover-art-4/i)
  await expect(page.getByText(/scene-prompts/i)).toBeVisible()
  await page.getByRole('button', { name: /Queue music video render/i }).click()
  await expect(page.getByText(/ComfyUI render worker blocked/i)).toBeVisible()
  await expect(page.getByText(/Stitch worker queued/i)).toBeVisible()
  await expect(page.getByText(/Lipsync QA worker queued/i)).toBeVisible()
  await expect(page.getByLabel(/Segment drift QA result/i)).toContainText(/Pending/i)
  await expect(page.getByLabel(/Post-stitch sync QA result/i)).toContainText(/Pending/i)
  await expect(page.getByText(/Music video source: task_generate-track-2/)).toBeVisible()
  await expect(page.getByText(/Source assets: asset-lyrics-draft/i)).toContainText(/asset-cover-art-4/i)
  await page.getByRole('button', { name: /Create video release pack/i }).click()
  await expect(page.getByRole('alert')).toContainText(/blocked until lipsync QA passes/i)
  await page.locator('button').filter({ hasText: 'Run lipsync QA' }).click()
  await expect(page.getByLabel(/Segment drift QA result/i)).toContainText(/Repair required/i)
  await expect(page.getByLabel(/Post-stitch sync QA result/i)).toContainText(/Repair required/i)
  await expect(page.getByLabel(/Exact lipsync failure ranges/i)).toBeVisible()
  await expect(page.getByText(/range-segmentDrift-1/i)).toBeVisible()
  await expect(page.getByText(/65s-108s/i).last()).toBeVisible()
  await page.getByRole('button', { name: /Queue repair pass/i }).click()
  await expect(page.getByText(/repair-1 queued/i)).toBeVisible()
  await page.locator('button').filter({ hasText: 'Run lipsync QA' }).click()
  await expect(page.locator('[aria-label="Video export gate state"]')).toContainText(/Video export ready/i)
  await expect(page.getByText(/repair-1 applied/i)).toBeVisible()
  await expect(page.getByRole('button', { name: /Run lipsync QA/i })).toBeDisabled()
  await expect(page.getByRole('button', { name: /Open music video lane/i })).toBeDisabled()
  await page.getByRole('button', { name: /Create video release pack/i }).click()
  await expect(page.getByRole('heading', { name: 'Release pack', exact: true })).toBeVisible()
  await expect(page.getByText(/Video included/i)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Package contents' })).toBeVisible()
  await expect(page.getByText(/lipsync-approved video/i)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Provenance receipts' })).toBeVisible()
  await expect(page.getByText(/lipsync-qa-passed/i)).toBeVisible()
  await page.getByRole('button', { name: /Plan archive-first cleanup/i }).click()
  await expect(page.getByText(/Cleanup archived/i)).toBeVisible()
  await expect(page.getByText(/archive-1/i)).toBeVisible()
  await page.getByRole('button', { name: /Apply cleanup/i }).click()
  await expect(page.getByText(/Cleanup applied/i)).toBeVisible()
  await expect(page.getByRole('button', { name: /Neon khaliji club hook provider take 1/i })).toBeHidden()
  await page.getByRole('button', { name: /Restore archived tracks/i }).click()
  await expect(page.getByText(/Cleanup restored/i)).toBeVisible()
  await expect(page.getByRole('button', { name: /Neon khaliji club hook provider take 1/i })).toBeVisible()
})

test('persists project workflow state across reload', async ({ page }, testInfo) => {
  const projectId = projectIdFor(testInfo)
  await page.goto(projectUrl(testInfo))
  await page.getByRole('textbox', { name: 'Brief' }).fill('Neon khaliji club hook')
  await page.getByRole('textbox', { name: 'Lyrics' }).fill('Verse pre chorus')
  await page.getByRole('textbox', { name: 'Style' }).fill('Gulf percussion and electro-pop')
  await page.getByRole('textbox', { name: 'Voice' }).fill('Consented bright tenor persona')
  await page.getByRole('button', { name: /Generate Suno batch/i }).click()
  await page.getByRole('button', { name: /Neon khaliji club hook provider take 2/i }).click()
  await page.locator('button').filter({ hasText: 'Open Song Lab' }).click()
  await page.getByRole('button', { name: /Lock hook region/i }).click()
  await page.getByRole('button', { name: /Queue replace section/i }).click()
  await page.getByRole('button', { name: /Save selected to local library/i }).click()
  await page.getByRole('button', { name: /Open music video lane/i }).click()
  await page.locator('button').filter({ hasText: 'Run lipsync QA' }).click()
  await page.getByRole('button', { name: /Queue repair pass/i }).click()
  await page.locator('button').filter({ hasText: 'Run lipsync QA' }).click()
  await page.getByRole('button', { name: /Create video release pack/i }).click()
  await page.getByRole('button', { name: /Plan archive-first cleanup/i }).click()
  await page.getByRole('button', { name: /Apply cleanup/i }).click()
  await page.getByRole('button', { name: /Downloads \/ exports/i }).click()
  await page.getByRole('button', { name: /Poll selected generation job/i }).click()

  await page.waitForFunction(async (id) => {
    const response = await fetch(`/api/projects/${encodeURIComponent(id)}`)
    const text = await response.text()
    return text.includes('"includesVideo":true') && text.includes('"status":"applied"') && text.includes('poll-task_generate')
  }, projectId)

  await page.reload()

  await page.getByRole('button', { name: /Open project lobby/i }).click()
  await expect(page.getByLabel(/Recent projects/i)).toContainText(/Neon khaliji club hook/i)
  await expect(page.getByRole('button', { name: /Release pack: Audio, video/i })).toBeVisible()

  await page.getByRole('button', { name: /Song Lab:/i }).click()
  await expect(page.getByText(/Hook locked/i)).toBeVisible()
  await expect(page.getByText(/songlab-edit-1 queued/i)).toBeVisible()

  await page.getByRole('button', { name: /Music video lane: Storyboard and lipsync QA opened from task_generate-track-2; video export ready/i }).click()
  await expect(page.locator('[aria-label="Video export gate state"]')).toContainText(/Video export ready/i)

  await page.getByRole('button', { name: /Local library:/i }).click()
  await expect(page.getByText(/task_generate-track-2 saved locally/i)).toBeVisible()

  await page.getByRole('button', { name: /Downloads \/ exports:/i }).click()
  await expect(page.getByText(/HTTP provider export route produced fixture downloadable outputs/i).first()).toBeVisible()
  await expect(page.getByText(/audio ready/i)).toBeVisible()

  await page.getByRole('button', { name: /Release pack: Audio, video/i }).click()
  await expect(page.getByText(/Video included/i)).toBeVisible()
  await expect(page.getByText(/Cleanup applied/i)).toBeVisible()
  await expect(page.locator('body')).not.toContainText(/apiKey|secret-key|bearer [A-Za-z0-9]/i)
})

test('opens Track Genealogy under the selected track workflow', async ({ page }, testInfo) => {
  await page.goto(projectUrl(testInfo))
  await page.getByRole('textbox', { name: 'Brief' }).fill('Neon khaliji club hook')
  await page.getByRole('textbox', { name: 'Lyrics' }).fill('Verse pre chorus with bilingual hook')
  await page.getByRole('textbox', { name: 'Style' }).fill('Gulf percussion and electro-pop')
  await page.getByRole('textbox', { name: 'Voice' }).fill('Consented bright tenor persona')
  await page.getByRole('button', { name: /Generate Suno batch/i }).click()
  await page.getByRole('button', { name: /Neon khaliji club hook provider take 2/i }).click()
  await page.getByRole('button', { name: /Version comparison/i }).click()
  await page.getByRole('button', { name: /Rate task_generate-track-2 as taste match/i }).click()
  await page.getByRole('button', { name: /Compare task_generate-track-1 vs task_generate-track-2/i }).click()
  await page.getByRole('button', { name: /Track Genealogy: Family tree/i }).click()

  await expect(page.getByRole('heading', { name: 'Track Genealogy' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Family Tree Graph' })).toBeVisible()
  await expect(page.getByLabel('Track Genealogy family tree graph')).toContainText(/Brief DNA/)
  await expect(page.getByLabel('Track Genealogy family tree graph')).toContainText(/task_generate-track-2/)
  await expect(page.getByRole('heading', { name: 'Trait Inspector' })).toBeVisible()
  await expect(page.getByLabel('Track Genealogy trait inspector')).toContainText(/vocal identity/)
  await expect(page.getByRole('heading', { name: 'Version Mutation Diff' })).toBeVisible()
  await expect(page.getByLabel('Track Genealogy mutation diff')).toContainText(/duration -4s vs selected source/)
  await expect(page.getByRole('heading', { name: 'Branch Fit Score' })).toBeVisible()
  await expect(page.getByLabel('Track Genealogy branch fit score')).toContainText(/task_generate-track-2 fit 5\/5/)
  await expect(page.getByRole('heading', { name: 'Reference DNA Import' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Archive/Prune Branches' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Generate From This Lineage' })).toBeVisible()
  await expect(page.getByLabel('Track Genealogy breeding suggestions')).toContainText(
    /combine task_generate-track-2 with task_generate-track-1/i,
  )
  await page.getByRole('button', { name: /Import reference DNA/i }).click()
  await expect(page.getByText(/asset-reference-audio-3 blocked/i)).toBeVisible()
  await expect(page.getByText(/reference-audio; Track Genealogy reference DNA; server/i)).toBeVisible()
  await page.getByRole('button', { name: /Track Genealogy: Family tree/i }).click()
  await page.getByRole('button', { name: /Generate from this lineage/i }).click()
  await expect(page.getByRole('button', { name: /Generation batch: 2 Suno variants from task_generate/i })).toBeVisible()
})
